### ISSUE TITLE
No files in this repo

### ISSUE THREAD

**Issue by murshed** [wptrainingteam/screencast#1]
Hi,
Good day.

In this repo, it has no files.

Want to know this software [screencast-o-matic](https://screencast-o-matic.com/) using for screencast or others?

Kind Regards

**Comment by JulieKuehl** [comment]
I'm not sure what this repo is for to be honest. Perhaps it is no longer needed as we are putting our screencast videos in our handbook rather than on GitHub.

**Comment by murshed** [comment]
My bad. I am sorry.
